### ISSUE TITLE
Error for floss

### ISSUE THREAD

**Issue by fareedfauzi** [CybercentreCanada/assemblyline-service-floss#1] opened 2020-07-22 08:41 UTC
I'm getting this error during analyze a sample
``` 
 File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/assemblyline_v4_service/common/base.py", line 79, in handle_task
    self.execute(request)
  File "/opt/al_service/floss/floss.py", line 153, in execute
    result_section = stack_result(section)
  File "/opt/al_service/floss/floss.py", line 65, in stack_result
    res = ResultSection(f"Group: '{min(group, key=len)}' Strings: {len(group)}", body='\n'.join(group),
ValueError: min() arg is an empty sequence
```

```
  File "/var/lib/assemblyline/.local/lib/python3.7/site-packages/assemblyline_v4_service/common/base.py", line 79, in handle_task
    self.execute(request)
  File "/opt/al_service/floss/floss.py", line 161, in execute
    raise RuntimeError(f'floss -n {enc_min_length} -x --no-static-strings --no-stack-strings '
RuntimeError: floss -n 7 -x --no-static-strings --no-stack-strings returned a non-zero exit status -9
stderr:
```

Error viewer:
![image](https://user-images.githubusercontent.com/56353946/88154913-fb53d980-cc39-11ea-9a87-353e42e83303.png)

![image](https://user-images.githubusercontent.com/56353946/88155007-1b839880-cc3a-11ea-80c0-262906c6da7a.png)

**Comment by cccs-jh** [comment] 2020-07-28 23:17
Thank you for submitting the error.  It was caused by a bug which is now fixed in Floss v4.0.0.beta6

**Closed by cccs-jh** 2020-07-28 23:17 UTC
